spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: mongodb://tmockadminun:tmockadminpswd@localhost:27017/auth-service?authSource=admin

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


server:
  port: 8093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
