spring:

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: notifications-service
          uri: lb://NOTIFICATIONS-SERVICE
          predicates:
              - Path=/api/notifications/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        # next
        #- id: user-service
        #  uri: lb:http://USER-SERVICE
        #  predicates:
        #    - Path=/api/v1/users/**
server:
  port: 8222


