spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: notifications-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.tmock.notificationsservice.kafka.user.UserCreationConfirmation

server:
  port: 8092


