spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: problem-service


aws:
  s3:
    endpoint: http://localhost:9000
    region: us-east-1
    accessKey: minio
    secretKey: minio12345
    usePathStyle: true
    bucket: cumock-problems

server:
  port: 8094