spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notifications-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: notifications-service       # ?????: listener ?????????? ? ???? ???????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"   # ???????? ?????? ??????
        # ????? ???????? ?????? type headers = true (??????), ?.?. ????? ????? ? FQN ?????????.
        spring.json.use.type.headers: true
      auto-offset-reset: latest

server:
  port: 8092

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.consumer: INFO